--------------------------------------------------------
--  Datei erstellt -Freitag-März-04-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table WVG_EINKOMMEN
--------------------------------------------------------

  CREATE TABLE "WOHNUNG"."WVG_EINKOMMEN" 
   (	"ID" NUMBER, 
	"EK_EINK_PERS_1" NUMBER(13,4), 
	"EK_EINK_PERS_2" NUMBER(13,4), 
	"EK_EINK_PERS_3" NUMBER(13,4), 
	"EK_EINK_PERS_4" NUMBER(13,4), 
	"EK_SONST_EINK" NUMBER(13,4), 
	"EK_ZAHLUNGSPFLICHT" NUMBER(13,4), 
	"EK_BETR_ZINSTILG" NUMBER(13,4), 
	"CREATED_BY" VARCHAR2(255 BYTE), 
	"CREATED_ON" TIMESTAMP (6), 
	"MODIFIED_BY" VARCHAR2(255 BYTE), 
	"MODIFIED_ON" TIMESTAMP (6), 
	"EK_ATS_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "WOHNUNG"."WVG_EINKOMMEN"."ID" IS 'Primäre Schlüssel';
   COMMENT ON COLUMN "WOHNUNG"."WVG_EINKOMMEN"."EK_EINK_PERS_1" IS 'Einkommen von Person 1 Haushalt';
   COMMENT ON COLUMN "WOHNUNG"."WVG_EINKOMMEN"."EK_EINK_PERS_2" IS 'Einkommen Person 2 Haushalt';
   COMMENT ON COLUMN "WOHNUNG"."WVG_EINKOMMEN"."EK_EINK_PERS_3" IS 'Einkommen Person 3 Haushalt';
   COMMENT ON COLUMN "WOHNUNG"."WVG_EINKOMMEN"."EK_EINK_PERS_4" IS 'Einkommen von  Person 4 Haushalt';
   COMMENT ON COLUMN "WOHNUNG"."WVG_EINKOMMEN"."EK_SONST_EINK" IS 'sonstige Einkünfte Personenhaushalt';
   COMMENT ON COLUMN "WOHNUNG"."WVG_EINKOMMEN"."EK_ZAHLUNGSPFLICHT" IS 'Zahlungsverpflichtungen';
   COMMENT ON COLUMN "WOHNUNG"."WVG_EINKOMMEN"."EK_BETR_ZINSTILG" IS 'übriger Betrag für Zinstilgung';
   COMMENT ON COLUMN "WOHNUNG"."WVG_EINKOMMEN"."CREATED_BY" IS 'Ersteller des jew.  Datensatzes';
   COMMENT ON COLUMN "WOHNUNG"."WVG_EINKOMMEN"."CREATED_ON" IS 'Timestamp Erstellung Datensatz';
   COMMENT ON COLUMN "WOHNUNG"."WVG_EINKOMMEN"."MODIFIED_BY" IS 'Benutzernamen v. Änderer Datensatz';
   COMMENT ON COLUMN "WOHNUNG"."WVG_EINKOMMEN"."MODIFIED_ON" IS 'Timestamp Änderung  Datensatz';
   COMMENT ON COLUMN "WOHNUNG"."WVG_EINKOMMEN"."EK_ATS_ID" IS 'Fremdschlüssel zu Antragssteller';
   COMMENT ON TABLE "WOHNUNG"."WVG_EINKOMMEN"  IS 'Daten zu Einkommen der Antragssteller';
REM INSERTING into WOHNUNG.WVG_EINKOMMEN
SET DEFINE OFF;
Insert into WOHNUNG.WVG_EINKOMMEN (ID,EK_EINK_PERS_1,EK_EINK_PERS_2,EK_EINK_PERS_3,EK_EINK_PERS_4,EK_SONST_EINK,EK_ZAHLUNGSPFLICHT,EK_BETR_ZINSTILG,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_ON,EK_ATS_ID) values ('3','50','10','20','30','10','100',null,'JUDITH.BORNHAUPT',to_timestamp('02.03.22 08:39:35,685757000','DD.MM.RR HH24:MI:SSXFF'),null,null,'10');
Insert into WOHNUNG.WVG_EINKOMMEN (ID,EK_EINK_PERS_1,EK_EINK_PERS_2,EK_EINK_PERS_3,EK_EINK_PERS_4,EK_SONST_EINK,EK_ZAHLUNGSPFLICHT,EK_BETR_ZINSTILG,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_ON,EK_ATS_ID) values ('4','50','10','20','30','10','100',null,'JUDITH.BORNHAUPT',to_timestamp('02.03.22 08:39:36,034805000','DD.MM.RR HH24:MI:SSXFF'),null,null,'10');
Insert into WOHNUNG.WVG_EINKOMMEN (ID,EK_EINK_PERS_1,EK_EINK_PERS_2,EK_EINK_PERS_3,EK_EINK_PERS_4,EK_SONST_EINK,EK_ZAHLUNGSPFLICHT,EK_BETR_ZINSTILG,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_ON,EK_ATS_ID) values ('5','10','20','30','40','10','50',null,'JUDITH.BORNHAUPT',to_timestamp('02.03.22 08:41:53,294847000','DD.MM.RR HH24:MI:SSXFF'),null,null,'5');
Insert into WOHNUNG.WVG_EINKOMMEN (ID,EK_EINK_PERS_1,EK_EINK_PERS_2,EK_EINK_PERS_3,EK_EINK_PERS_4,EK_SONST_EINK,EK_ZAHLUNGSPFLICHT,EK_BETR_ZINSTILG,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_ON,EK_ATS_ID) values ('6','50','30','20','10','40','80',null,'JUDITH.BORNHAUPT',to_timestamp('02.03.22 08:57:06,231519000','DD.MM.RR HH24:MI:SSXFF'),null,null,'2');
Insert into WOHNUNG.WVG_EINKOMMEN (ID,EK_EINK_PERS_1,EK_EINK_PERS_2,EK_EINK_PERS_3,EK_EINK_PERS_4,EK_SONST_EINK,EK_ZAHLUNGSPFLICHT,EK_BETR_ZINSTILG,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_ON,EK_ATS_ID) values ('1','60','100','10','20','100','10','280','JUDITH.BORNHAUPT',to_timestamp('28.02.22 13:03:32,979518000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',to_timestamp('04.03.22 10:09:47,095097000','DD.MM.RR HH24:MI:SSXFF'),'1');
Insert into WOHNUNG.WVG_EINKOMMEN (ID,EK_EINK_PERS_1,EK_EINK_PERS_2,EK_EINK_PERS_3,EK_EINK_PERS_4,EK_SONST_EINK,EK_ZAHLUNGSPFLICHT,EK_BETR_ZINSTILG,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_ON,EK_ATS_ID) values ('2','50','100','50','10','50','100','160','JUDITH.BORNHAUPT',to_timestamp('01.03.22 07:00:32,453130000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',to_timestamp('01.03.22 10:08:55,661072000','DD.MM.RR HH24:MI:SSXFF'),'4');
Insert into WOHNUNG.WVG_EINKOMMEN (ID,EK_EINK_PERS_1,EK_EINK_PERS_2,EK_EINK_PERS_3,EK_EINK_PERS_4,EK_SONST_EINK,EK_ZAHLUNGSPFLICHT,EK_BETR_ZINSTILG,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_ON,EK_ATS_ID) values ('7','50','30','20','10','80','100','90','JUDITH.BORNHAUPT',to_timestamp('02.03.22 09:00:53,095502000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',to_timestamp('02.03.22 09:27:41,263934000','DD.MM.RR HH24:MI:SSXFF'),'3');
Insert into WOHNUNG.WVG_EINKOMMEN (ID,EK_EINK_PERS_1,EK_EINK_PERS_2,EK_EINK_PERS_3,EK_EINK_PERS_4,EK_SONST_EINK,EK_ZAHLUNGSPFLICHT,EK_BETR_ZINSTILG,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_ON,EK_ATS_ID) values ('8','50','100','100','200','50','100','400','JUDITH.BORNHAUPT',to_timestamp('02.03.22 13:39:47,856795000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',to_timestamp('02.03.22 13:39:47,857948000','DD.MM.RR HH24:MI:SSXFF'),'9');
--------------------------------------------------------
--  DDL for Index PRIMARYKEYEINKOMMEN
--------------------------------------------------------

  CREATE UNIQUE INDEX "WOHNUNG"."PRIMARYKEYEINKOMMEN" ON "WOHNUNG"."WVG_EINKOMMEN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRIG_WVG_EINKOMMEN
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "WOHNUNG"."TRIG_WVG_EINKOMMEN" 
BEFORE UPDATE OR INSERT ON WVG_EINKOMMEN 
FOR EACH ROW 
BEGIN 
IF :new.id is NULL
THEN 
 SELECT to_number(seq_wvg_einkommen.NEXTVAL) INTO :new.id FROM dual;
END IF;
    IF inserting THEN
        :new.created_on := localtimestamp;
        :new.created_by := nvl(wwv_flow.g_user,user);
    END IF;
IF updating THEN
:new.modified_on := localtimestamp;
:new.modified_by := nvl(wwv_flow.g_user,user);
    END IF;
END;
/
ALTER TRIGGER "WOHNUNG"."TRIG_WVG_EINKOMMEN" ENABLE;
--------------------------------------------------------
--  Constraints for Table WVG_EINKOMMEN
--------------------------------------------------------

  ALTER TABLE "WOHNUNG"."WVG_EINKOMMEN" ADD CONSTRAINT "PRIMARYKEYEINKOMMEN" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "WOHNUNG"."WVG_EINKOMMEN" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table WVG_EINKOMMEN
--------------------------------------------------------

  ALTER TABLE "WOHNUNG"."WVG_EINKOMMEN" ADD CONSTRAINT "FRK_EK_ATS_ID" FOREIGN KEY ("EK_ATS_ID")
	  REFERENCES "WOHNUNG"."WVG_ANTRAGSSTELLER" ("ID") ON DELETE CASCADE ENABLE;
