--------------------------------------------------------
--  Datei erstellt -Freitag-März-04-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table WVG_BETRIEBSZUGEHOERIGKEIT
--------------------------------------------------------

  CREATE TABLE "WOHNUNG"."WVG_BETRIEBSZUGEHOERIGKEIT" 
   (	"ID" NUMBER, 
	"BZG_AKT_WOHNORT" VARCHAR2(200 BYTE), 
	"BZG_BISH_WOHNORT" VARCHAR2(200 BYTE), 
	"BZG_IN_AUSB" VARCHAR2(4 BYTE), 
	"BZG_END_AUSB" DATE, 
	"BZG_FRUEHERE" VARCHAR2(4 BYTE), 
	"BZG_STA_FRUEHERE" DATE, 
	"BZG_END_FRUEHERE" DATE, 
	"BZG_RUHESTAND" VARCHAR2(4 BYTE), 
	"BZG_TEILZEIT" VARCHAR2(4 BYTE), 
	"BZG_GRUND_TEILZEIT" VARCHAR2(1000 BYTE), 
	"BZG_BEG_VHLTNIS" DATE, 
	"BZG_BEFRISTUNG" DATE, 
	"BZG_VOLLZEIT" VARCHAR2(4 BYTE), 
	"BZG_PROBEZEIT" VARCHAR2(4 BYTE), 
	"BZG_ENDE_PROBEZEIT" DATE, 
	"CREATED_ON" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 BYTE), 
	"MODIFIED_ON" TIMESTAMP (6), 
	"MODIFIED_BY" VARCHAR2(255 BYTE), 
	"BZG_OERTLICHE_VERS" VARCHAR2(4 BYTE), 
	"BZG_ATS_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "WOHNUNG"."WVG_BETRIEBSZUGEHOERIGKEIT"."ID" IS 'primäre Schlüssel';
   COMMENT ON COLUMN "WOHNUNG"."WVG_BETRIEBSZUGEHOERIGKEIT"."BZG_AKT_WOHNORT" IS 'aktuelle Wohnorte der Antragssteller';
   COMMENT ON COLUMN "WOHNUNG"."WVG_BETRIEBSZUGEHOERIGKEIT"."BZG_BISH_WOHNORT" IS 'bisherige Wohnorte der Antragssteller';
   COMMENT ON COLUMN "WOHNUNG"."WVG_BETRIEBSZUGEHOERIGKEIT"."BZG_IN_AUSB" IS 'ist Antragssteller in Ausbildung?';
   COMMENT ON COLUMN "WOHNUNG"."WVG_BETRIEBSZUGEHOERIGKEIT"."BZG_END_AUSB" IS 'wann endet Ausbildung?';
   COMMENT ON COLUMN "WOHNUNG"."WVG_BETRIEBSZUGEHOERIGKEIT"."BZG_FRUEHERE" IS 'früher Arbeitsverh. mit Bezirk?';
   COMMENT ON COLUMN "WOHNUNG"."WVG_BETRIEBSZUGEHOERIGKEIT"."BZG_STA_FRUEHERE" IS 'wann begann früheres Arbeitsverhältnis?';
   COMMENT ON COLUMN "WOHNUNG"."WVG_BETRIEBSZUGEHOERIGKEIT"."BZG_END_FRUEHERE" IS 'wann endete früheres Arbeitsverhältnis?';
   COMMENT ON COLUMN "WOHNUNG"."WVG_BETRIEBSZUGEHOERIGKEIT"."BZG_RUHESTAND" IS 'ist  Antragssteller  im Ruhestand?';
   COMMENT ON COLUMN "WOHNUNG"."WVG_BETRIEBSZUGEHOERIGKEIT"."BZG_TEILZEIT" IS 'arbeitet  Antragssteller in Teilzeit?';
   COMMENT ON COLUMN "WOHNUNG"."WVG_BETRIEBSZUGEHOERIGKEIT"."BZG_GRUND_TEILZEIT" IS 'grund für teilzeitbeschäftigung';
   COMMENT ON COLUMN "WOHNUNG"."WVG_BETRIEBSZUGEHOERIGKEIT"."BZG_BEG_VHLTNIS" IS 'beginn derzeitiges Arbeitsverhältnis';
   COMMENT ON COLUMN "WOHNUNG"."WVG_BETRIEBSZUGEHOERIGKEIT"."BZG_BEFRISTUNG" IS 'bis wann arbeitsverhältnis befristet?';
   COMMENT ON COLUMN "WOHNUNG"."WVG_BETRIEBSZUGEHOERIGKEIT"."BZG_VOLLZEIT" IS 'beschäftigung in vollzeit?';
   COMMENT ON COLUMN "WOHNUNG"."WVG_BETRIEBSZUGEHOERIGKEIT"."BZG_PROBEZEIT" IS 'aktuell in probezeit?';
   COMMENT ON COLUMN "WOHNUNG"."WVG_BETRIEBSZUGEHOERIGKEIT"."BZG_ENDE_PROBEZEIT" IS 'ende probezeit';
   COMMENT ON COLUMN "WOHNUNG"."WVG_BETRIEBSZUGEHOERIGKEIT"."CREATED_ON" IS 'Timestamp Erstellung Datensatz';
   COMMENT ON COLUMN "WOHNUNG"."WVG_BETRIEBSZUGEHOERIGKEIT"."CREATED_BY" IS 'Ersteller Datensatz';
   COMMENT ON COLUMN "WOHNUNG"."WVG_BETRIEBSZUGEHOERIGKEIT"."MODIFIED_ON" IS 'Timestamp Änderung Datensatz';
   COMMENT ON COLUMN "WOHNUNG"."WVG_BETRIEBSZUGEHOERIGKEIT"."MODIFIED_BY" IS 'Benutzernamen vom  Änderer Datensatz';
   COMMENT ON COLUMN "WOHNUNG"."WVG_BETRIEBSZUGEHOERIGKEIT"."BZG_OERTLICHE_VERS" IS 'ob jeweils eine örtliche versetzung stattfand';
   COMMENT ON COLUMN "WOHNUNG"."WVG_BETRIEBSZUGEHOERIGKEIT"."BZG_ATS_ID" IS 'Fremdschlüssel zu Antragsssteller';
   COMMENT ON TABLE "WOHNUNG"."WVG_BETRIEBSZUGEHOERIGKEIT"  IS 'Daten zu Betriebszugehoerigkeit der Antragssteller';
REM INSERTING into WOHNUNG.WVG_BETRIEBSZUGEHOERIGKEIT
SET DEFINE OFF;
Insert into WOHNUNG.WVG_BETRIEBSZUGEHOERIGKEIT (ID,BZG_AKT_WOHNORT,BZG_BISH_WOHNORT,BZG_IN_AUSB,BZG_END_AUSB,BZG_FRUEHERE,BZG_STA_FRUEHERE,BZG_END_FRUEHERE,BZG_RUHESTAND,BZG_TEILZEIT,BZG_GRUND_TEILZEIT,BZG_BEG_VHLTNIS,BZG_BEFRISTUNG,BZG_VOLLZEIT,BZG_PROBEZEIT,BZG_ENDE_PROBEZEIT,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,BZG_OERTLICHE_VERS,BZG_ATS_ID) values ('2',null,null,'ja',null,'ja',to_date('02.03.22','DD.MM.RR'),null,'ja','ja',null,to_date('09.03.22','DD.MM.RR'),to_date('07.03.22','DD.MM.RR'),'nein','ja',null,to_timestamp('01.03.22 06:58:18,589261000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',to_timestamp('01.03.22 12:22:16,197803000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT','nein','4');
Insert into WOHNUNG.WVG_BETRIEBSZUGEHOERIGKEIT (ID,BZG_AKT_WOHNORT,BZG_BISH_WOHNORT,BZG_IN_AUSB,BZG_END_AUSB,BZG_FRUEHERE,BZG_STA_FRUEHERE,BZG_END_FRUEHERE,BZG_RUHESTAND,BZG_TEILZEIT,BZG_GRUND_TEILZEIT,BZG_BEG_VHLTNIS,BZG_BEFRISTUNG,BZG_VOLLZEIT,BZG_PROBEZEIT,BZG_ENDE_PROBEZEIT,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,BZG_OERTLICHE_VERS,BZG_ATS_ID) values ('1',null,null,'3',null,'nein',null,null,null,null,null,to_date('01.02.22','DD.MM.RR'),null,null,'ja',null,to_timestamp('28.02.22 12:44:05,586101000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',to_timestamp('02.03.22 14:18:53,669353000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',null,'1');
Insert into WOHNUNG.WVG_BETRIEBSZUGEHOERIGKEIT (ID,BZG_AKT_WOHNORT,BZG_BISH_WOHNORT,BZG_IN_AUSB,BZG_END_AUSB,BZG_FRUEHERE,BZG_STA_FRUEHERE,BZG_END_FRUEHERE,BZG_RUHESTAND,BZG_TEILZEIT,BZG_GRUND_TEILZEIT,BZG_BEG_VHLTNIS,BZG_BEFRISTUNG,BZG_VOLLZEIT,BZG_PROBEZEIT,BZG_ENDE_PROBEZEIT,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,BZG_OERTLICHE_VERS,BZG_ATS_ID) values ('3',null,null,'4',null,null,null,null,null,null,null,null,null,null,'ja',null,to_timestamp('01.03.22 10:53:28,060254000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',to_timestamp('02.03.22 14:19:31,837979000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT','3','2');
Insert into WOHNUNG.WVG_BETRIEBSZUGEHOERIGKEIT (ID,BZG_AKT_WOHNORT,BZG_BISH_WOHNORT,BZG_IN_AUSB,BZG_END_AUSB,BZG_FRUEHERE,BZG_STA_FRUEHERE,BZG_END_FRUEHERE,BZG_RUHESTAND,BZG_TEILZEIT,BZG_GRUND_TEILZEIT,BZG_BEG_VHLTNIS,BZG_BEFRISTUNG,BZG_VOLLZEIT,BZG_PROBEZEIT,BZG_ENDE_PROBEZEIT,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,BZG_OERTLICHE_VERS,BZG_ATS_ID) values ('4',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_timestamp('01.03.22 12:45:03,556114000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',to_timestamp('01.03.22 15:27:26,112347000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',null,'6');
Insert into WOHNUNG.WVG_BETRIEBSZUGEHOERIGKEIT (ID,BZG_AKT_WOHNORT,BZG_BISH_WOHNORT,BZG_IN_AUSB,BZG_END_AUSB,BZG_FRUEHERE,BZG_STA_FRUEHERE,BZG_END_FRUEHERE,BZG_RUHESTAND,BZG_TEILZEIT,BZG_GRUND_TEILZEIT,BZG_BEG_VHLTNIS,BZG_BEFRISTUNG,BZG_VOLLZEIT,BZG_PROBEZEIT,BZG_ENDE_PROBEZEIT,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,BZG_OERTLICHE_VERS,BZG_ATS_ID) values ('5',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_timestamp('01.03.22 12:46:55,750151000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',null,null,null,'7');
Insert into WOHNUNG.WVG_BETRIEBSZUGEHOERIGKEIT (ID,BZG_AKT_WOHNORT,BZG_BISH_WOHNORT,BZG_IN_AUSB,BZG_END_AUSB,BZG_FRUEHERE,BZG_STA_FRUEHERE,BZG_END_FRUEHERE,BZG_RUHESTAND,BZG_TEILZEIT,BZG_GRUND_TEILZEIT,BZG_BEG_VHLTNIS,BZG_BEFRISTUNG,BZG_VOLLZEIT,BZG_PROBEZEIT,BZG_ENDE_PROBEZEIT,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,BZG_OERTLICHE_VERS,BZG_ATS_ID) values ('6',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_timestamp('01.03.22 12:48:51,869646000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',null,null,null,'8');
Insert into WOHNUNG.WVG_BETRIEBSZUGEHOERIGKEIT (ID,BZG_AKT_WOHNORT,BZG_BISH_WOHNORT,BZG_IN_AUSB,BZG_END_AUSB,BZG_FRUEHERE,BZG_STA_FRUEHERE,BZG_END_FRUEHERE,BZG_RUHESTAND,BZG_TEILZEIT,BZG_GRUND_TEILZEIT,BZG_BEG_VHLTNIS,BZG_BEFRISTUNG,BZG_VOLLZEIT,BZG_PROBEZEIT,BZG_ENDE_PROBEZEIT,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,BZG_OERTLICHE_VERS,BZG_ATS_ID) values ('7',null,null,'ja',null,'ja',null,null,'ja','ja',null,to_date('02.03.22','DD.MM.RR'),to_date('24.03.22','DD.MM.RR'),'ja','ja',null,to_timestamp('02.03.22 08:06:02,216772000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',null,null,'ja','10');
Insert into WOHNUNG.WVG_BETRIEBSZUGEHOERIGKEIT (ID,BZG_AKT_WOHNORT,BZG_BISH_WOHNORT,BZG_IN_AUSB,BZG_END_AUSB,BZG_FRUEHERE,BZG_STA_FRUEHERE,BZG_END_FRUEHERE,BZG_RUHESTAND,BZG_TEILZEIT,BZG_GRUND_TEILZEIT,BZG_BEG_VHLTNIS,BZG_BEFRISTUNG,BZG_VOLLZEIT,BZG_PROBEZEIT,BZG_ENDE_PROBEZEIT,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,BZG_OERTLICHE_VERS,BZG_ATS_ID) values ('8',null,null,null,null,null,null,null,null,null,null,null,null,null,'3',null,to_timestamp('02.03.22 14:20:37,028140000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',null,null,null,'11');
--------------------------------------------------------
--  DDL for Index PRIMARYKEYBETRIEBSZUGEH
--------------------------------------------------------

  CREATE UNIQUE INDEX "WOHNUNG"."PRIMARYKEYBETRIEBSZUGEH" ON "WOHNUNG"."WVG_BETRIEBSZUGEHOERIGKEIT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRIG_WVG_BETRIEBSZUGEH
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "WOHNUNG"."TRIG_WVG_BETRIEBSZUGEH" 
BEFORE INSERT OR UPDATE ON WVG_BETRIEBSZUGEHOERIGKEIT 
FOR EACH ROW 
BEGIN 
IF :new.id is NULL
THEN 
 SELECT to_number(seq_wvg_betriebszugehoerigkeit.NEXTVAL) INTO :new.id FROM dual;
END IF;
    IF inserting THEN
        :new.created_on := localtimestamp;
        :new.created_by := nvl(wwv_flow.g_user,user);
    END IF;
IF updating THEN
:new.modified_on := localtimestamp;
:new.modified_by := nvl(wwv_flow.g_user,user);
    END IF;
END;
/
ALTER TRIGGER "WOHNUNG"."TRIG_WVG_BETRIEBSZUGEH" ENABLE;
--------------------------------------------------------
--  Constraints for Table WVG_BETRIEBSZUGEHOERIGKEIT
--------------------------------------------------------

  ALTER TABLE "WOHNUNG"."WVG_BETRIEBSZUGEHOERIGKEIT" ADD CONSTRAINT "PRIMARYKEYBETRIEBSZUGEH" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WVG_BETRIEBSZUGEHOERIGKEIT
--------------------------------------------------------

  ALTER TABLE "WOHNUNG"."WVG_BETRIEBSZUGEHOERIGKEIT" ADD CONSTRAINT "FRK_WVG_BETRIEBSZUGEH_ATS_ID" FOREIGN KEY ("BZG_ATS_ID")
	  REFERENCES "WOHNUNG"."WVG_ANTRAGSSTELLER" ("ID") ON DELETE CASCADE ENABLE;
