--------------------------------------------------------
--  Datei erstellt -Freitag-März-04-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table WVG_KIND
--------------------------------------------------------

  CREATE TABLE "WOHNUNG"."WVG_KIND" 
   (	"ID" NUMBER, 
	"KIN_ALTER" NUMBER, 
	"KIN_UMFANG_HAUSHALT" VARCHAR2(10 BYTE), 
	"CREATED_BY" VARCHAR2(255 BYTE), 
	"CREATED_ON" TIMESTAMP (6), 
	"MODIFIED_BY" VARCHAR2(255 BYTE), 
	"MODIFIED_ON" TIMESTAMP (6), 
	"KIN_ATS_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "WOHNUNG"."WVG_KIND"."ID" IS 'Primäre Schlüssel';
   COMMENT ON COLUMN "WOHNUNG"."WVG_KIND"."KIN_ALTER" IS 'Alter Kind ';
   COMMENT ON COLUMN "WOHNUNG"."WVG_KIND"."KIN_UMFANG_HAUSHALT" IS 'Zeitanteil  Kind  im Haushalt';
   COMMENT ON COLUMN "WOHNUNG"."WVG_KIND"."CREATED_BY" IS 'Ersteller Datensatz';
   COMMENT ON COLUMN "WOHNUNG"."WVG_KIND"."CREATED_ON" IS 'Timestamp Erstellung  Datensatz';
   COMMENT ON COLUMN "WOHNUNG"."WVG_KIND"."MODIFIED_BY" IS 'Benutzernamen v. Änderer Datensatz';
   COMMENT ON COLUMN "WOHNUNG"."WVG_KIND"."MODIFIED_ON" IS 'Timestamp Änderung  Datensatz';
   COMMENT ON COLUMN "WOHNUNG"."WVG_KIND"."KIN_ATS_ID" IS 'Fremdschlüssel Antragssteller';
   COMMENT ON TABLE "WOHNUNG"."WVG_KIND"  IS 'Daten zu Kindern der Antragssteller';
REM INSERTING into WOHNUNG.WVG_KIND
SET DEFINE OFF;
Insert into WOHNUNG.WVG_KIND (ID,KIN_ALTER,KIN_UMFANG_HAUSHALT,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_ON,KIN_ATS_ID) values ('3','10','dauerhaft','JUDITH.BORNHAUPT',to_timestamp('02.03.22 08:27:56,804308000','DD.MM.RR HH24:MI:SSXFF'),null,null,'10');
Insert into WOHNUNG.WVG_KIND (ID,KIN_ALTER,KIN_UMFANG_HAUSHALT,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_ON,KIN_ATS_ID) values ('1','10','teilweise','JUDITH.BORNHAUPT',to_timestamp('28.02.22 12:56:05,347907000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',to_timestamp('01.03.22 14:35:31,248818000','DD.MM.RR HH24:MI:SSXFF'),'1');
Insert into WOHNUNG.WVG_KIND (ID,KIN_ALTER,KIN_UMFANG_HAUSHALT,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_ON,KIN_ATS_ID) values ('2','15','teilweise','JUDITH.BORNHAUPT',to_timestamp('01.03.22 07:00:00,191085000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',to_timestamp('01.03.22 07:01:03,864421000','DD.MM.RR HH24:MI:SSXFF'),'4');
--------------------------------------------------------
--  DDL for Index PRIMARYKEYKIND
--------------------------------------------------------

  CREATE UNIQUE INDEX "WOHNUNG"."PRIMARYKEYKIND" ON "WOHNUNG"."WVG_KIND" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRIG_WVG_KIND
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "WOHNUNG"."TRIG_WVG_KIND" 
BEFORE INSERT OR UPDATE ON WVG_KIND 
FOR EACH ROW 
BEGIN 
IF :new.id is NULL
THEN 
 SELECT to_number(SEQ_WVG_kind.nextval) INTO :new.id FROM dual;
END IF;
    IF inserting THEN
        :new.created_on := localtimestamp;
        :new.created_by := nvl(wwv_flow.g_user,user);
    END IF;
IF updating THEN
:new.modified_on := localtimestamp;
:new.modified_by := nvl(wwv_flow.g_user,user);
    END IF;
END;
/
ALTER TRIGGER "WOHNUNG"."TRIG_WVG_KIND" ENABLE;
--------------------------------------------------------
--  Constraints for Table WVG_KIND
--------------------------------------------------------

  ALTER TABLE "WOHNUNG"."WVG_KIND" ADD CONSTRAINT "PRIMARYKEYKIND" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "WOHNUNG"."WVG_KIND" MODIFY ("ID" NOT NULL ENABLE);
