--------------------------------------------------------
--  Datei erstellt -Freitag-März-04-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table WVG_WOHNUNG_ANTRAGSSTELLER
--------------------------------------------------------

  CREATE TABLE "WOHNUNG"."WVG_WOHNUNG_ANTRAGSSTELLER" 
   (	"ID" NUMBER, 
	"WHA_BEANTRAGT" VARCHAR2(4 BYTE), 
	"WHA_BESICHTIGT" VARCHAR2(4 BYTE), 
	"WHA_WHG_ID" NUMBER, 
	"WHA_ATS_ID" NUMBER, 
	"CREATED_ON" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 BYTE), 
	"MODIFIED_ON" TIMESTAMP (6), 
	"MODIFIED_BY" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "WOHNUNG"."WVG_WOHNUNG_ANTRAGSSTELLER"."ID" IS 'primäre Schlüssel';
   COMMENT ON COLUMN "WOHNUNG"."WVG_WOHNUNG_ANTRAGSSTELLER"."WHA_BEANTRAGT" IS 'wohnung vom antragssteller beantragt?';
   COMMENT ON COLUMN "WOHNUNG"."WVG_WOHNUNG_ANTRAGSSTELLER"."WHA_BESICHTIGT" IS 'wohnung vom antragssteller besichtigt?';
   COMMENT ON COLUMN "WOHNUNG"."WVG_WOHNUNG_ANTRAGSSTELLER"."WHA_WHG_ID" IS 'fremdschlüssel zu wohnung';
   COMMENT ON COLUMN "WOHNUNG"."WVG_WOHNUNG_ANTRAGSSTELLER"."WHA_ATS_ID" IS 'fremdschlüssel zu Antragssteller';
   COMMENT ON COLUMN "WOHNUNG"."WVG_WOHNUNG_ANTRAGSSTELLER"."CREATED_ON" IS 'Erstelldatum Datensatz';
   COMMENT ON COLUMN "WOHNUNG"."WVG_WOHNUNG_ANTRAGSSTELLER"."CREATED_BY" IS 'Ersteller Datensatz';
   COMMENT ON COLUMN "WOHNUNG"."WVG_WOHNUNG_ANTRAGSSTELLER"."MODIFIED_ON" IS 'Timestamp Änderung';
   COMMENT ON COLUMN "WOHNUNG"."WVG_WOHNUNG_ANTRAGSSTELLER"."MODIFIED_BY" IS 'Benutzernamen vom Änderer Datensatz';
   COMMENT ON TABLE "WOHNUNG"."WVG_WOHNUNG_ANTRAGSSTELLER"  IS 'Verbindungsdaten (m:n)  Antragssteller Wohnung';
REM INSERTING into WOHNUNG.WVG_WOHNUNG_ANTRAGSSTELLER
SET DEFINE OFF;
Insert into WOHNUNG.WVG_WOHNUNG_ANTRAGSSTELLER (ID,WHA_BEANTRAGT,WHA_BESICHTIGT,WHA_WHG_ID,WHA_ATS_ID,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY) values ('2',null,null,'1','2',to_timestamp('28.02.22 12:41:29,265230000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',null,null);
Insert into WOHNUNG.WVG_WOHNUNG_ANTRAGSSTELLER (ID,WHA_BEANTRAGT,WHA_BESICHTIGT,WHA_WHG_ID,WHA_ATS_ID,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY) values ('3',null,null,'1','3',to_timestamp('28.02.22 12:59:56,387592000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',null,null);
Insert into WOHNUNG.WVG_WOHNUNG_ANTRAGSSTELLER (ID,WHA_BEANTRAGT,WHA_BESICHTIGT,WHA_WHG_ID,WHA_ATS_ID,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY) values ('4',null,null,'1','4',to_timestamp('01.03.22 06:56:14,315591000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',to_timestamp('02.03.22 10:02:35,773979000','DD.MM.RR HH24:MI:SSXFF'),'ROD42201');
Insert into WOHNUNG.WVG_WOHNUNG_ANTRAGSSTELLER (ID,WHA_BEANTRAGT,WHA_BESICHTIGT,WHA_WHG_ID,WHA_ATS_ID,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY) values ('5',null,null,'1','5',to_timestamp('01.03.22 10:27:28,472858000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',null,null);
Insert into WOHNUNG.WVG_WOHNUNG_ANTRAGSSTELLER (ID,WHA_BEANTRAGT,WHA_BESICHTIGT,WHA_WHG_ID,WHA_ATS_ID,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY) values ('6','ja','nein','2','6',to_timestamp('01.03.22 12:30:12,027283000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',to_timestamp('01.03.22 15:26:55,297350000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT');
Insert into WOHNUNG.WVG_WOHNUNG_ANTRAGSSTELLER (ID,WHA_BEANTRAGT,WHA_BESICHTIGT,WHA_WHG_ID,WHA_ATS_ID,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY) values ('7','ja','ja','2','7',to_timestamp('01.03.22 12:39:31,851691000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',null,null);
Insert into WOHNUNG.WVG_WOHNUNG_ANTRAGSSTELLER (ID,WHA_BEANTRAGT,WHA_BESICHTIGT,WHA_WHG_ID,WHA_ATS_ID,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY) values ('8','ja','nein','2','8',to_timestamp('01.03.22 12:48:24,306886000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',null,null);
Insert into WOHNUNG.WVG_WOHNUNG_ANTRAGSSTELLER (ID,WHA_BEANTRAGT,WHA_BESICHTIGT,WHA_WHG_ID,WHA_ATS_ID,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY) values ('9','ja','ja','1','9',to_timestamp('01.03.22 15:13:22,263461000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',null,null);
Insert into WOHNUNG.WVG_WOHNUNG_ANTRAGSSTELLER (ID,WHA_BEANTRAGT,WHA_BESICHTIGT,WHA_WHG_ID,WHA_ATS_ID,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY) values ('10','ja','ja','5','4',to_timestamp('01.03.22 18:20:40,868097000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',null,null);
Insert into WOHNUNG.WVG_WOHNUNG_ANTRAGSSTELLER (ID,WHA_BEANTRAGT,WHA_BESICHTIGT,WHA_WHG_ID,WHA_ATS_ID,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY) values ('11','ja','nein','1','10',to_timestamp('02.03.22 08:01:14,350833000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',to_timestamp('02.03.22 08:39:04,270218000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT');
Insert into WOHNUNG.WVG_WOHNUNG_ANTRAGSSTELLER (ID,WHA_BEANTRAGT,WHA_BESICHTIGT,WHA_WHG_ID,WHA_ATS_ID,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY) values ('12',null,null,'1','11',to_timestamp('02.03.22 14:20:16,939219000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',null,null);
Insert into WOHNUNG.WVG_WOHNUNG_ANTRAGSSTELLER (ID,WHA_BEANTRAGT,WHA_BESICHTIGT,WHA_WHG_ID,WHA_ATS_ID,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY) values ('1','ja','ja','1','1',to_timestamp('28.02.22 12:28:40,137376000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',to_timestamp('28.02.22 12:41:11,925282000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT');
--------------------------------------------------------
--  DDL for Trigger TRIG_WVG_WOHNUNG_ANTRAGSST
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "WOHNUNG"."TRIG_WVG_WOHNUNG_ANTRAGSST" 
BEFORE UPDATE OR INSERT ON WVG_WOHNUNG_ANTRAGSSTELLER 
FOR EACH ROW 
BEGIN 
IF :new.id is NULL
THEN 
 SELECT to_number(SEQ_WVG_WOHNUNG_ANTRAGSSTELLER.nextval) INTO :new.id FROM dual;
END IF;
    IF inserting THEN
        :new.created_on := localtimestamp;
        :new.created_by := nvl(wwv_flow.g_user,user);
    END IF;
IF updating THEN
:new.modified_on := localtimestamp;
:new.modified_by := nvl(wwv_flow.g_user,user);
    END IF;
END;
/
ALTER TRIGGER "WOHNUNG"."TRIG_WVG_WOHNUNG_ANTRAGSST" ENABLE;
--------------------------------------------------------
--  Constraints for Table WVG_WOHNUNG_ANTRAGSSTELLER
--------------------------------------------------------

  ALTER TABLE "WOHNUNG"."WVG_WOHNUNG_ANTRAGSSTELLER" ADD CONSTRAINT "PRIMARYKEYWHGAN" PRIMARY KEY ("ID") DISABLE;
--------------------------------------------------------
--  Ref Constraints for Table WVG_WOHNUNG_ANTRAGSSTELLER
--------------------------------------------------------

  ALTER TABLE "WOHNUNG"."WVG_WOHNUNG_ANTRAGSSTELLER" ADD CONSTRAINT "FRK_WVG_WHG_ANTRAGSST_ATS_ID" FOREIGN KEY ("WHA_ATS_ID")
	  REFERENCES "WOHNUNG"."WVG_ANTRAGSSTELLER" ("ID") ON DELETE CASCADE ENABLE;
