--------------------------------------------------------
--  Datei erstellt -Freitag-März-04-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table WVG_PUNKTE
--------------------------------------------------------

  CREATE TABLE "WOHNUNG"."WVG_PUNKTE" 
   (	"ID" NUMBER, 
	"PNT_VERSETZUNG" NUMBER, 
	"PNT_FRUEHERE" NUMBER, 
	"PNT_AUSBILDUNG" NUMBER, 
	"PNT_RUHESTAND" NUMBER, 
	"PNT_TEILZEIT" NUMBER, 
	"PNT_BEG_VERHAELTNIS" NUMBER, 
	"PNT_BEFRISTUNG" NUMBER, 
	"PNT_VOLLZEIT" NUMBER, 
	"PNT_PROBEZEIT" NUMBER, 
	"PNT_BEW_BEZIRKSWHG" NUMBER, 
	"PNT_SCHWERBEHINDERUNG" NUMBER, 
	"PNT_ENTF_ARBEITSPLATZ" NUMBER, 
	"PNT_GESU_GRUENDE" NUMBER, 
	"PNT_WHGSKUENDIGUNG" NUMBER, 
	"PNT_SONSTIGE_GRUENDE" NUMBER, 
	"PNT_PFLEGE_ANGEH" NUMBER, 
	"PNT_WOHNS_DT" NUMBER, 
	"PNT_VERSCHIEDENGESCHL" NUMBER, 
	"PNT_KD_DAUERHAFT_AZ" NUMBER, 
	"PNT_KD_TEILWEISE_AZ" NUMBER, 
	"CREATED_BY" VARCHAR2(255 BYTE), 
	"CREATED_ON" TIMESTAMP (6), 
	"MODIFIED_BY" VARCHAR2(255 BYTE), 
	"MODIFIED_ON" TIMESTAMP (6), 
	"PNT_ATS_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "WOHNUNG"."WVG_PUNKTE"."ID" IS 'Primäre Schlüssel';
   COMMENT ON COLUMN "WOHNUNG"."WVG_PUNKTE"."PNT_VERSETZUNG" IS 'punkte für Versetzung';
   COMMENT ON COLUMN "WOHNUNG"."WVG_PUNKTE"."PNT_FRUEHERE" IS 'Punkte früheres Arbeitsverhältnis';
   COMMENT ON COLUMN "WOHNUNG"."WVG_PUNKTE"."PNT_AUSBILDUNG" IS 'Punkte für Ausbildung';
   COMMENT ON COLUMN "WOHNUNG"."WVG_PUNKTE"."PNT_RUHESTAND" IS 'Punkte für Ruhestand';
   COMMENT ON COLUMN "WOHNUNG"."WVG_PUNKTE"."PNT_TEILZEIT" IS 'Punkte für Teilzeitbeschäftigung';
   COMMENT ON COLUMN "WOHNUNG"."WVG_PUNKTE"."PNT_BEG_VERHAELTNIS" IS 'Punkte Datum Beginn  Arbeitsverhältnis';
   COMMENT ON COLUMN "WOHNUNG"."WVG_PUNKTE"."PNT_VOLLZEIT" IS 'Punkte Vollzeitbeschäftigung';
   COMMENT ON COLUMN "WOHNUNG"."WVG_PUNKTE"."PNT_PROBEZEIT" IS 'Punkte Probezeit';
   COMMENT ON COLUMN "WOHNUNG"."WVG_PUNKTE"."PNT_BEW_BEZIRKSWHG" IS 'Punkte bewohnen Bezirkswohnung';
   COMMENT ON COLUMN "WOHNUNG"."WVG_PUNKTE"."PNT_SCHWERBEHINDERUNG" IS 'Punkte Schwerbehinderung';
   COMMENT ON COLUMN "WOHNUNG"."WVG_PUNKTE"."PNT_ENTF_ARBEITSPLATZ" IS 'Punkte Entfernung Arbeitsplatz';
   COMMENT ON COLUMN "WOHNUNG"."WVG_PUNKTE"."PNT_GESU_GRUENDE" IS 'Punkte gesundheitliche Gründe';
   COMMENT ON COLUMN "WOHNUNG"."WVG_PUNKTE"."PNT_WHGSKUENDIGUNG" IS 'Punkte Wohnungskündigung';
   COMMENT ON COLUMN "WOHNUNG"."WVG_PUNKTE"."PNT_SONSTIGE_GRUENDE" IS 'Punkte sonstige Gründe Wohnungswechsel';
   COMMENT ON COLUMN "WOHNUNG"."WVG_PUNKTE"."PNT_PFLEGE_ANGEH" IS 'Punkte Pflege Angehörige';
   COMMENT ON COLUMN "WOHNUNG"."WVG_PUNKTE"."PNT_WOHNS_DT" IS 'Punkte Personenanzahl mit Wohnsitz Deutschland';
   COMMENT ON COLUMN "WOHNUNG"."WVG_PUNKTE"."PNT_VERSCHIEDENGESCHL" IS 'Punkte verschiedengeschlechtliche Kinder';
   COMMENT ON COLUMN "WOHNUNG"."WVG_PUNKTE"."PNT_KD_DAUERHAFT_AZ" IS 'Punkte Kinder dauerhaft im Haushalt';
   COMMENT ON COLUMN "WOHNUNG"."WVG_PUNKTE"."PNT_KD_TEILWEISE_AZ" IS 'Punkte Kinder teilweise im Haushalt';
   COMMENT ON COLUMN "WOHNUNG"."WVG_PUNKTE"."CREATED_BY" IS 'Ersteller Datensatz';
   COMMENT ON COLUMN "WOHNUNG"."WVG_PUNKTE"."CREATED_ON" IS 'Timestamp Erstellung Datensatz';
   COMMENT ON COLUMN "WOHNUNG"."WVG_PUNKTE"."MODIFIED_BY" IS 'Benutzernamen Änderer Datensatz';
   COMMENT ON COLUMN "WOHNUNG"."WVG_PUNKTE"."MODIFIED_ON" IS 'Timestamp Änderung  Datensatz';
   COMMENT ON COLUMN "WOHNUNG"."WVG_PUNKTE"."PNT_ATS_ID" IS 'Fremdschlüssel zu Antragssteller';
   COMMENT ON TABLE "WOHNUNG"."WVG_PUNKTE"  IS 'Daten zu erhaltenen Punkten der  Antragssteller';
REM INSERTING into WOHNUNG.WVG_PUNKTE
SET DEFINE OFF;
Insert into WOHNUNG.WVG_PUNKTE (ID,PNT_VERSETZUNG,PNT_FRUEHERE,PNT_AUSBILDUNG,PNT_RUHESTAND,PNT_TEILZEIT,PNT_BEG_VERHAELTNIS,PNT_BEFRISTUNG,PNT_VOLLZEIT,PNT_PROBEZEIT,PNT_BEW_BEZIRKSWHG,PNT_SCHWERBEHINDERUNG,PNT_ENTF_ARBEITSPLATZ,PNT_GESU_GRUENDE,PNT_WHGSKUENDIGUNG,PNT_SONSTIGE_GRUENDE,PNT_PFLEGE_ANGEH,PNT_WOHNS_DT,PNT_VERSCHIEDENGESCHL,PNT_KD_DAUERHAFT_AZ,PNT_KD_TEILWEISE_AZ,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_ON,PNT_ATS_ID) values ('2','8','9','2','3','7','5','6','4','1',null,null,null,null,null,null,null,'1','2','3','4','JUDITH.BORNHAUPT',to_timestamp('01.03.22 06:58:18,594247000','DD.MM.RR HH24:MI:SSXFF'),'ROD42201',to_timestamp('02.03.22 10:03:39,818663000','DD.MM.RR HH24:MI:SSXFF'),'4');
Insert into WOHNUNG.WVG_PUNKTE (ID,PNT_VERSETZUNG,PNT_FRUEHERE,PNT_AUSBILDUNG,PNT_RUHESTAND,PNT_TEILZEIT,PNT_BEG_VERHAELTNIS,PNT_BEFRISTUNG,PNT_VOLLZEIT,PNT_PROBEZEIT,PNT_BEW_BEZIRKSWHG,PNT_SCHWERBEHINDERUNG,PNT_ENTF_ARBEITSPLATZ,PNT_GESU_GRUENDE,PNT_WHGSKUENDIGUNG,PNT_SONSTIGE_GRUENDE,PNT_PFLEGE_ANGEH,PNT_WOHNS_DT,PNT_VERSCHIEDENGESCHL,PNT_KD_DAUERHAFT_AZ,PNT_KD_TEILWEISE_AZ,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_ON,PNT_ATS_ID) values ('3','8','9','2','3','4','5','6','4','1','1','3','4','2','6','7','5','1','2','3','4','JUDITH.BORNHAUPT',to_timestamp('01.03.22 10:53:28,061943000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',to_timestamp('02.03.22 14:19:31,839944000','DD.MM.RR HH24:MI:SSXFF'),'2');
Insert into WOHNUNG.WVG_PUNKTE (ID,PNT_VERSETZUNG,PNT_FRUEHERE,PNT_AUSBILDUNG,PNT_RUHESTAND,PNT_TEILZEIT,PNT_BEG_VERHAELTNIS,PNT_BEFRISTUNG,PNT_VOLLZEIT,PNT_PROBEZEIT,PNT_BEW_BEZIRKSWHG,PNT_SCHWERBEHINDERUNG,PNT_ENTF_ARBEITSPLATZ,PNT_GESU_GRUENDE,PNT_WHGSKUENDIGUNG,PNT_SONSTIGE_GRUENDE,PNT_PFLEGE_ANGEH,PNT_WOHNS_DT,PNT_VERSCHIEDENGESCHL,PNT_KD_DAUERHAFT_AZ,PNT_KD_TEILWEISE_AZ,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_ON,PNT_ATS_ID) values ('4','8','9','2','3','7','5','6','4','1','1','3','4','2','6','7','5','1','2','3','4','JUDITH.BORNHAUPT',to_timestamp('01.03.22 12:45:03,557806000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',to_timestamp('01.03.22 15:27:26,115601000','DD.MM.RR HH24:MI:SSXFF'),'6');
Insert into WOHNUNG.WVG_PUNKTE (ID,PNT_VERSETZUNG,PNT_FRUEHERE,PNT_AUSBILDUNG,PNT_RUHESTAND,PNT_TEILZEIT,PNT_BEG_VERHAELTNIS,PNT_BEFRISTUNG,PNT_VOLLZEIT,PNT_PROBEZEIT,PNT_BEW_BEZIRKSWHG,PNT_SCHWERBEHINDERUNG,PNT_ENTF_ARBEITSPLATZ,PNT_GESU_GRUENDE,PNT_WHGSKUENDIGUNG,PNT_SONSTIGE_GRUENDE,PNT_PFLEGE_ANGEH,PNT_WOHNS_DT,PNT_VERSCHIEDENGESCHL,PNT_KD_DAUERHAFT_AZ,PNT_KD_TEILWEISE_AZ,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_ON,PNT_ATS_ID) values ('5','7','8','2','3',null,'4','5','4','1',null,null,null,null,null,null,null,null,null,null,null,'JUDITH.BORNHAUPT',to_timestamp('01.03.22 12:46:55,750596000','DD.MM.RR HH24:MI:SSXFF'),null,null,'7');
Insert into WOHNUNG.WVG_PUNKTE (ID,PNT_VERSETZUNG,PNT_FRUEHERE,PNT_AUSBILDUNG,PNT_RUHESTAND,PNT_TEILZEIT,PNT_BEG_VERHAELTNIS,PNT_BEFRISTUNG,PNT_VOLLZEIT,PNT_PROBEZEIT,PNT_BEW_BEZIRKSWHG,PNT_SCHWERBEHINDERUNG,PNT_ENTF_ARBEITSPLATZ,PNT_GESU_GRUENDE,PNT_WHGSKUENDIGUNG,PNT_SONSTIGE_GRUENDE,PNT_PFLEGE_ANGEH,PNT_WOHNS_DT,PNT_VERSCHIEDENGESCHL,PNT_KD_DAUERHAFT_AZ,PNT_KD_TEILWEISE_AZ,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_ON,PNT_ATS_ID) values ('6','8','9','2','3','7','5','6','4','1',null,null,null,null,null,null,null,null,null,null,null,'JUDITH.BORNHAUPT',to_timestamp('01.03.22 12:48:51,870895000','DD.MM.RR HH24:MI:SSXFF'),null,null,'8');
Insert into WOHNUNG.WVG_PUNKTE (ID,PNT_VERSETZUNG,PNT_FRUEHERE,PNT_AUSBILDUNG,PNT_RUHESTAND,PNT_TEILZEIT,PNT_BEG_VERHAELTNIS,PNT_BEFRISTUNG,PNT_VOLLZEIT,PNT_PROBEZEIT,PNT_BEW_BEZIRKSWHG,PNT_SCHWERBEHINDERUNG,PNT_ENTF_ARBEITSPLATZ,PNT_GESU_GRUENDE,PNT_WHGSKUENDIGUNG,PNT_SONSTIGE_GRUENDE,PNT_PFLEGE_ANGEH,PNT_WOHNS_DT,PNT_VERSCHIEDENGESCHL,PNT_KD_DAUERHAFT_AZ,PNT_KD_TEILWEISE_AZ,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_ON,PNT_ATS_ID) values ('7','8','9','2','3','7','5','6','4','1','1','3','4','2','6','8','5','1','2','3','4','JUDITH.BORNHAUPT',to_timestamp('02.03.22 08:06:02,220245000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',to_timestamp('02.03.22 14:08:49,284201000','DD.MM.RR HH24:MI:SSXFF'),'10');
Insert into WOHNUNG.WVG_PUNKTE (ID,PNT_VERSETZUNG,PNT_FRUEHERE,PNT_AUSBILDUNG,PNT_RUHESTAND,PNT_TEILZEIT,PNT_BEG_VERHAELTNIS,PNT_BEFRISTUNG,PNT_VOLLZEIT,PNT_PROBEZEIT,PNT_BEW_BEZIRKSWHG,PNT_SCHWERBEHINDERUNG,PNT_ENTF_ARBEITSPLATZ,PNT_GESU_GRUENDE,PNT_WHGSKUENDIGUNG,PNT_SONSTIGE_GRUENDE,PNT_PFLEGE_ANGEH,PNT_WOHNS_DT,PNT_VERSCHIEDENGESCHL,PNT_KD_DAUERHAFT_AZ,PNT_KD_TEILWEISE_AZ,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_ON,PNT_ATS_ID) values ('8',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,'JUDITH.BORNHAUPT',to_timestamp('02.03.22 14:20:37,029852000','DD.MM.RR HH24:MI:SSXFF'),null,null,'11');
Insert into WOHNUNG.WVG_PUNKTE (ID,PNT_VERSETZUNG,PNT_FRUEHERE,PNT_AUSBILDUNG,PNT_RUHESTAND,PNT_TEILZEIT,PNT_BEG_VERHAELTNIS,PNT_BEFRISTUNG,PNT_VOLLZEIT,PNT_PROBEZEIT,PNT_BEW_BEZIRKSWHG,PNT_SCHWERBEHINDERUNG,PNT_ENTF_ARBEITSPLATZ,PNT_GESU_GRUENDE,PNT_WHGSKUENDIGUNG,PNT_SONSTIGE_GRUENDE,PNT_PFLEGE_ANGEH,PNT_WOHNS_DT,PNT_VERSCHIEDENGESCHL,PNT_KD_DAUERHAFT_AZ,PNT_KD_TEILWEISE_AZ,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_ON,PNT_ATS_ID) values ('1','8','9','2','3','7','5','6','4','1','1','3','4','2','6','7','5','1','2','3','4','JUDITH.BORNHAUPT',to_timestamp('28.02.22 12:44:05,589909000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',to_timestamp('02.03.22 14:18:53,670751000','DD.MM.RR HH24:MI:SSXFF'),'1');
--------------------------------------------------------
--  DDL for Index PRIMARYKEYPUNKTE
--------------------------------------------------------

  CREATE UNIQUE INDEX "WOHNUNG"."PRIMARYKEYPUNKTE" ON "WOHNUNG"."WVG_PUNKTE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRIG_WVG_PUNKTE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "WOHNUNG"."TRIG_WVG_PUNKTE" 
BEFORE INSERT OR UPDATE ON WVG_PUNKTE 
FOR EACH ROW 
BEGIN 
IF :new.id is NULL
THEN 
 SELECT to_number(seq_wvg_punkte.NEXTVAL) INTO :new.id FROM dual;
END IF;
    IF inserting THEN
        :new.created_on := localtimestamp;
        :new.created_by := nvl(wwv_flow.g_user,user);
    END IF;
IF updating THEN
:new.modified_on := localtimestamp;
:new.modified_by := nvl(wwv_flow.g_user,user);
    END IF;
END;
/
ALTER TRIGGER "WOHNUNG"."TRIG_WVG_PUNKTE" ENABLE;
--------------------------------------------------------
--  Constraints for Table WVG_PUNKTE
--------------------------------------------------------

  ALTER TABLE "WOHNUNG"."WVG_PUNKTE" ADD CONSTRAINT "PRIMARYKEYPUNKTE" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "WOHNUNG"."WVG_PUNKTE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table WVG_PUNKTE
--------------------------------------------------------

  ALTER TABLE "WOHNUNG"."WVG_PUNKTE" ADD CONSTRAINT "FRK_WVG_PUNKTE_ATS_ID" FOREIGN KEY ("PNT_ATS_ID")
	  REFERENCES "WOHNUNG"."WVG_ANTRAGSSTELLER" ("ID") ON DELETE CASCADE ENABLE;
