--------------------------------------------------------
--  Datei erstellt -Freitag-März-04-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table WVG_FILES
--------------------------------------------------------

  CREATE TABLE "WOHNUNG"."WVG_FILES" 
   (	"ID" NUMBER, 
	"FIL_FREMD_ART" VARCHAR2(20 BYTE), 
	"FIL_FREMD_ID" NUMBER, 
	"FIL_FILENAME" VARCHAR2(255 BYTE), 
	"FIL_FILE_MIMETYPE" VARCHAR2(20 BYTE), 
	"FIL_FILE_CHARSET" VARCHAR2(20 BYTE), 
	"FIL_FILE_BLOB" BLOB, 
	"FIL_COMMENTS" VARCHAR2(20 BYTE), 
	"CREATED_ON" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(20 BYTE), 
	"MODIFIED_ON" TIMESTAMP (6), 
	"MODIFIED_BY" VARCHAR2(20 BYTE), 
	"FIL_ATS_ID" NUMBER, 
	"FIL_KENNZ" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("FIL_FILE_BLOB") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into WOHNUNG.WVG_FILES
SET DEFINE OFF;
Insert into WOHNUNG.WVG_FILES (ID,FIL_FREMD_ART,FIL_FREMD_ID,FIL_FILENAME,FIL_FILE_MIMETYPE,FIL_FILE_CHARSET,FIL_COMMENTS,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,FIL_ATS_ID,FIL_KENNZ) values ('9',null,null,'impfzertifikat.jpg',null,null,'hallo',to_timestamp('01.03.22 09:02:00,485826000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',to_timestamp('03.03.22 15:44:46,223468000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT','1','2');
Insert into WOHNUNG.WVG_FILES (ID,FIL_FREMD_ART,FIL_FREMD_ID,FIL_FILENAME,FIL_FILE_MIMETYPE,FIL_FILE_CHARSET,FIL_COMMENTS,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,FIL_ATS_ID,FIL_KENNZ) values ('10',null,null,null,null,null,null,to_timestamp('02.03.22 12:49:07,049269000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',null,null,null,null);
Insert into WOHNUNG.WVG_FILES (ID,FIL_FREMD_ART,FIL_FREMD_ID,FIL_FILENAME,FIL_FILE_MIMETYPE,FIL_FILE_CHARSET,FIL_COMMENTS,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,FIL_ATS_ID,FIL_KENNZ) values ('11',null,null,null,null,null,'kind',to_timestamp('02.03.22 13:03:15,219722000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',null,null,null,null);
Insert into WOHNUNG.WVG_FILES (ID,FIL_FREMD_ART,FIL_FREMD_ID,FIL_FILENAME,FIL_FILE_MIMETYPE,FIL_FILE_CHARSET,FIL_COMMENTS,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,FIL_ATS_ID,FIL_KENNZ) values ('8',null,null,null,null,null,'hiha',to_timestamp('01.03.22 08:54:58,726433000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',to_timestamp('01.03.22 09:38:35,784411000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT','4','2');
Insert into WOHNUNG.WVG_FILES (ID,FIL_FREMD_ART,FIL_FREMD_ID,FIL_FILENAME,FIL_FILE_MIMETYPE,FIL_FILE_CHARSET,FIL_COMMENTS,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,FIL_ATS_ID,FIL_KENNZ) values ('12',null,null,null,null,null,'kind',to_timestamp('02.03.22 13:04:42,380520000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',null,null,null,null);
Insert into WOHNUNG.WVG_FILES (ID,FIL_FREMD_ART,FIL_FREMD_ID,FIL_FILENAME,FIL_FILE_MIMETYPE,FIL_FILE_CHARSET,FIL_COMMENTS,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,FIL_ATS_ID,FIL_KENNZ) values ('13',null,null,null,null,null,'marian',to_timestamp('02.03.22 13:06:37,134045000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',to_timestamp('02.03.22 17:01:29,882305000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT','1','1');
Insert into WOHNUNG.WVG_FILES (ID,FIL_FREMD_ART,FIL_FREMD_ID,FIL_FILENAME,FIL_FILE_MIMETYPE,FIL_FILE_CHARSET,FIL_COMMENTS,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,FIL_ATS_ID,FIL_KENNZ) values ('14',null,null,null,null,null,null,to_timestamp('02.03.22 13:19:24,792672000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',to_timestamp('03.03.22 15:42:14,416912000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT','1','5');
Insert into WOHNUNG.WVG_FILES (ID,FIL_FREMD_ART,FIL_FREMD_ID,FIL_FILENAME,FIL_FILE_MIMETYPE,FIL_FILE_CHARSET,FIL_COMMENTS,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,FIL_ATS_ID,FIL_KENNZ) values ('15',null,null,null,null,null,null,to_timestamp('02.03.22 13:19:45,844503000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',to_timestamp('03.03.22 15:53:59,225843000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT','1','4');
Insert into WOHNUNG.WVG_FILES (ID,FIL_FREMD_ART,FIL_FREMD_ID,FIL_FILENAME,FIL_FILE_MIMETYPE,FIL_FILE_CHARSET,FIL_COMMENTS,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,FIL_ATS_ID,FIL_KENNZ) values ('16',null,null,null,null,null,'maria',to_timestamp('02.03.22 13:20:08,062447000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',null,null,'1','3');
Insert into WOHNUNG.WVG_FILES (ID,FIL_FREMD_ART,FIL_FREMD_ID,FIL_FILENAME,FIL_FILE_MIMETYPE,FIL_FILE_CHARSET,FIL_COMMENTS,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,FIL_ATS_ID,FIL_KENNZ) values ('17',null,null,null,null,null,null,to_timestamp('03.03.22 15:57:15,494898000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',null,null,'1','4');
Insert into WOHNUNG.WVG_FILES (ID,FIL_FREMD_ART,FIL_FREMD_ID,FIL_FILENAME,FIL_FILE_MIMETYPE,FIL_FILE_CHARSET,FIL_COMMENTS,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,FIL_ATS_ID,FIL_KENNZ) values ('18',null,null,null,null,null,null,to_timestamp('03.03.22 16:00:14,939995000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',null,null,'1','3');
Insert into WOHNUNG.WVG_FILES (ID,FIL_FREMD_ART,FIL_FREMD_ID,FIL_FILENAME,FIL_FILE_MIMETYPE,FIL_FILE_CHARSET,FIL_COMMENTS,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,FIL_ATS_ID,FIL_KENNZ) values ('19',null,null,null,null,null,null,to_timestamp('03.03.22 16:02:02,899674000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',to_timestamp('03.03.22 16:02:02,899924000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT','1','4');
Insert into WOHNUNG.WVG_FILES (ID,FIL_FREMD_ART,FIL_FREMD_ID,FIL_FILENAME,FIL_FILE_MIMETYPE,FIL_FILE_CHARSET,FIL_COMMENTS,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,FIL_ATS_ID,FIL_KENNZ) values ('21',null,null,null,null,null,null,to_timestamp('03.03.22 16:07:56,381040000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',to_timestamp('03.03.22 16:07:56,381242000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT','1','4');
Insert into WOHNUNG.WVG_FILES (ID,FIL_FREMD_ART,FIL_FREMD_ID,FIL_FILENAME,FIL_FILE_MIMETYPE,FIL_FILE_CHARSET,FIL_COMMENTS,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,FIL_ATS_ID,FIL_KENNZ) values ('22',null,null,'Auffrischungsimpfung.jpg',null,null,null,to_timestamp('03.03.22 16:19:59,547489000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',to_timestamp('03.03.22 16:19:59,551436000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT','1','4');
Insert into WOHNUNG.WVG_FILES (ID,FIL_FREMD_ART,FIL_FREMD_ID,FIL_FILENAME,FIL_FILE_MIMETYPE,FIL_FILE_CHARSET,FIL_COMMENTS,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,FIL_ATS_ID,FIL_KENNZ) values ('23',null,null,'Erstimpfung.jpg',null,null,null,to_timestamp('03.03.22 16:28:55,641497000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',to_timestamp('03.03.22 16:28:55,645246000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT','1','4');
Insert into WOHNUNG.WVG_FILES (ID,FIL_FREMD_ART,FIL_FREMD_ID,FIL_FILENAME,FIL_FILE_MIMETYPE,FIL_FILE_CHARSET,FIL_COMMENTS,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,FIL_ATS_ID,FIL_KENNZ) values ('24',null,null,'Erstimpfung.jpg',null,null,null,to_timestamp('03.03.22 16:29:14,354280000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',to_timestamp('03.03.22 16:29:14,354732000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT','1','4');
Insert into WOHNUNG.WVG_FILES (ID,FIL_FREMD_ART,FIL_FREMD_ID,FIL_FILENAME,FIL_FILE_MIMETYPE,FIL_FILE_CHARSET,FIL_COMMENTS,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,FIL_ATS_ID,FIL_KENNZ) values ('26',null,null,'Auffrischungsimpfung.jpg',null,null,'auffrischungsimpfung',to_timestamp('03.03.22 16:33:08,958015000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',to_timestamp('03.03.22 16:33:08,958425000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT','1','4');
Insert into WOHNUNG.WVG_FILES (ID,FIL_FREMD_ART,FIL_FREMD_ID,FIL_FILENAME,FIL_FILE_MIMETYPE,FIL_FILE_CHARSET,FIL_COMMENTS,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,FIL_ATS_ID,FIL_KENNZ) values ('27',null,null,'Zweitimpfung.jpg',null,null,'zweitimpfung',to_timestamp('03.03.22 16:35:04,777253000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',to_timestamp('03.03.22 16:35:04,777697000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT','1','3');
Insert into WOHNUNG.WVG_FILES (ID,FIL_FREMD_ART,FIL_FREMD_ID,FIL_FILENAME,FIL_FILE_MIMETYPE,FIL_FILE_CHARSET,FIL_COMMENTS,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,FIL_ATS_ID,FIL_KENNZ) values ('28',null,null,'Zweitimpfung.jpg',null,null,'zweitimpfung',to_timestamp('03.03.22 16:36:56,067288000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',to_timestamp('03.03.22 16:36:56,067789000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT','1','4');
Insert into WOHNUNG.WVG_FILES (ID,FIL_FREMD_ART,FIL_FREMD_ID,FIL_FILENAME,FIL_FILE_MIMETYPE,FIL_FILE_CHARSET,FIL_COMMENTS,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,FIL_ATS_ID,FIL_KENNZ) values ('29',null,null,'ansichtOrderingOnly.PNG',null,null,'ordering',to_timestamp('03.03.22 16:37:20,470848000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',to_timestamp('03.03.22 16:37:20,471221000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT','1','4');
Insert into WOHNUNG.WVG_FILES (ID,FIL_FREMD_ART,FIL_FREMD_ID,FIL_FILENAME,FIL_FILE_MIMETYPE,FIL_FILE_CHARSET,FIL_COMMENTS,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,FIL_ATS_ID,FIL_KENNZ) values ('25',null,null,'impfzertifikat.jpg',null,null,null,to_timestamp('03.03.22 16:32:41,092075000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',to_timestamp('03.03.22 16:32:41,092608000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT','1','4');
--------------------------------------------------------
--  DDL for Index PRIMARYKEYFILES
--------------------------------------------------------

  CREATE UNIQUE INDEX "WOHNUNG"."PRIMARYKEYFILES" ON "WOHNUNG"."WVG_FILES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRIG_WVG_FILES
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "WOHNUNG"."TRIG_WVG_FILES" 
BEFORE INSERT OR UPDATE ON WVG_files 
FOR EACH ROW 
BEGIN 
IF :new.id is NULL
THEN 
 SELECT to_number(seq_wvg_files.NEXTVAL) INTO :new.id FROM dual;
END IF;
    IF inserting THEN
        :new.created_on := localtimestamp;
        :new.created_by := nvl(wwv_flow.g_user,user);
    END IF;
IF updating THEN
:new.modified_on := localtimestamp;
:new.modified_by := nvl(wwv_flow.g_user,user);
    END IF;
END;
/
ALTER TRIGGER "WOHNUNG"."TRIG_WVG_FILES" ENABLE;
--------------------------------------------------------
--  Constraints for Table WVG_FILES
--------------------------------------------------------

  ALTER TABLE "WOHNUNG"."WVG_FILES" ADD CONSTRAINT "PRIMARYKEYFILES" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
