--------------------------------------------------------
--  Datei erstellt -Freitag-März-04-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table WVG_SOZIALE_ANGELEGENHEIT
--------------------------------------------------------

  CREATE TABLE "WOHNUNG"."WVG_SOZIALE_ANGELEGENHEIT" 
   (	"ID" NUMBER, 
	"SAG_SONSTIGE_GRUENDE" VARCHAR2(4 BYTE), 
	"SAG_SONSTIGE_GR_TXT" VARCHAR2(1000 BYTE), 
	"SAG_BEW_BEZIRKSWHG" VARCHAR2(4 BYTE), 
	"SAG_SCHWERBEHINDERUNG" VARCHAR2(4 BYTE), 
	"SAG_GDHL_GRUENDE" VARCHAR2(4 BYTE), 
	"SAG_WOHNUNGSKUENDIGUNG" VARCHAR2(4 BYTE), 
	"SAG_GR_WHGKUENDIGUNG" VARCHAR2(1000 BYTE), 
	"SAG_PFLEGE_ANGEH" VARCHAR2(4 BYTE), 
	"CREATED_ON" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 BYTE), 
	"MODIFIED_BY" VARCHAR2(255 BYTE), 
	"MODIFIED_ON" TIMESTAMP (6), 
	"SAG_ATS_ID" NUMBER, 
	"SAG_ENTF_ARBEITSPLATZ" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "WOHNUNG"."WVG_SOZIALE_ANGELEGENHEIT"."ID" IS 'primäre Schlüssel';
   COMMENT ON COLUMN "WOHNUNG"."WVG_SOZIALE_ANGELEGENHEIT"."SAG_SONSTIGE_GRUENDE" IS 'sonstige Gründe Wohnungswechsel';
   COMMENT ON COLUMN "WOHNUNG"."WVG_SOZIALE_ANGELEGENHEIT"."SAG_SONSTIGE_GR_TXT" IS 'Beschreibung sonstige Gründe';
   COMMENT ON COLUMN "WOHNUNG"."WVG_SOZIALE_ANGELEGENHEIT"."SAG_BEW_BEZIRKSWHG" IS 'bewohnt Bezirkswohnung?';
   COMMENT ON COLUMN "WOHNUNG"."WVG_SOZIALE_ANGELEGENHEIT"."SAG_SCHWERBEHINDERUNG" IS 'Schwerbehinderung?';
   COMMENT ON COLUMN "WOHNUNG"."WVG_SOZIALE_ANGELEGENHEIT"."SAG_GDHL_GRUENDE" IS 'gesundheitliche Gründe für  Wohnungswechsel?';
   COMMENT ON COLUMN "WOHNUNG"."WVG_SOZIALE_ANGELEGENHEIT"."SAG_WOHNUNGSKUENDIGUNG" IS 'vorliegen wohnungskündigung?';
   COMMENT ON COLUMN "WOHNUNG"."WVG_SOZIALE_ANGELEGENHEIT"."SAG_GR_WHGKUENDIGUNG" IS 'grund für wohnungskündigung';
   COMMENT ON COLUMN "WOHNUNG"."WVG_SOZIALE_ANGELEGENHEIT"."SAG_PFLEGE_ANGEH" IS 'pflege angehöriger >=1 Jahr im Haushalt?';
   COMMENT ON COLUMN "WOHNUNG"."WVG_SOZIALE_ANGELEGENHEIT"."CREATED_ON" IS 'Timestamp Erstellung Datensatz';
   COMMENT ON COLUMN "WOHNUNG"."WVG_SOZIALE_ANGELEGENHEIT"."CREATED_BY" IS 'Ersteller Datensatz';
   COMMENT ON COLUMN "WOHNUNG"."WVG_SOZIALE_ANGELEGENHEIT"."MODIFIED_BY" IS 'Benutzername Änderer Datensatz';
   COMMENT ON COLUMN "WOHNUNG"."WVG_SOZIALE_ANGELEGENHEIT"."MODIFIED_ON" IS 'Timestamp Änderung Datensatz';
   COMMENT ON COLUMN "WOHNUNG"."WVG_SOZIALE_ANGELEGENHEIT"."SAG_ATS_ID" IS 'Fremdschlüssel zu Antragssteller';
   COMMENT ON TABLE "WOHNUNG"."WVG_SOZIALE_ANGELEGENHEIT"  IS 'Daten zu sozialen Angelegenheiten der Antragssteller';
REM INSERTING into WOHNUNG.WVG_SOZIALE_ANGELEGENHEIT
SET DEFINE OFF;
Insert into WOHNUNG.WVG_SOZIALE_ANGELEGENHEIT (ID,SAG_SONSTIGE_GRUENDE,SAG_SONSTIGE_GR_TXT,SAG_BEW_BEZIRKSWHG,SAG_SCHWERBEHINDERUNG,SAG_GDHL_GRUENDE,SAG_WOHNUNGSKUENDIGUNG,SAG_GR_WHGKUENDIGUNG,SAG_PFLEGE_ANGEH,CREATED_ON,CREATED_BY,MODIFIED_BY,MODIFIED_ON,SAG_ATS_ID,SAG_ENTF_ARBEITSPLATZ) values ('3',null,null,null,null,null,null,null,null,to_timestamp('01.03.22 10:55:13,831380000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',null,null,'2',null);
Insert into WOHNUNG.WVG_SOZIALE_ANGELEGENHEIT (ID,SAG_SONSTIGE_GRUENDE,SAG_SONSTIGE_GR_TXT,SAG_BEW_BEZIRKSWHG,SAG_SCHWERBEHINDERUNG,SAG_GDHL_GRUENDE,SAG_WOHNUNGSKUENDIGUNG,SAG_GR_WHGKUENDIGUNG,SAG_PFLEGE_ANGEH,CREATED_ON,CREATED_BY,MODIFIED_BY,MODIFIED_ON,SAG_ATS_ID,SAG_ENTF_ARBEITSPLATZ) values ('4',null,null,null,null,null,null,null,null,to_timestamp('01.03.22 12:46:11,597375000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',null,null,'6',null);
Insert into WOHNUNG.WVG_SOZIALE_ANGELEGENHEIT (ID,SAG_SONSTIGE_GRUENDE,SAG_SONSTIGE_GR_TXT,SAG_BEW_BEZIRKSWHG,SAG_SCHWERBEHINDERUNG,SAG_GDHL_GRUENDE,SAG_WOHNUNGSKUENDIGUNG,SAG_GR_WHGKUENDIGUNG,SAG_PFLEGE_ANGEH,CREATED_ON,CREATED_BY,MODIFIED_BY,MODIFIED_ON,SAG_ATS_ID,SAG_ENTF_ARBEITSPLATZ) values ('5',null,null,'ja',null,null,null,null,null,to_timestamp('02.03.22 08:27:06,971537000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT','JUDITH.BORNHAUPT',to_timestamp('02.03.22 14:08:49,283994000','DD.MM.RR HH24:MI:SSXFF'),'10',null);
Insert into WOHNUNG.WVG_SOZIALE_ANGELEGENHEIT (ID,SAG_SONSTIGE_GRUENDE,SAG_SONSTIGE_GR_TXT,SAG_BEW_BEZIRKSWHG,SAG_SCHWERBEHINDERUNG,SAG_GDHL_GRUENDE,SAG_WOHNUNGSKUENDIGUNG,SAG_GR_WHGKUENDIGUNG,SAG_PFLEGE_ANGEH,CREATED_ON,CREATED_BY,MODIFIED_BY,MODIFIED_ON,SAG_ATS_ID,SAG_ENTF_ARBEITSPLATZ) values ('1',null,null,'ja',null,null,null,null,null,to_timestamp('28.02.22 12:54:27,109408000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT','JUDITH.BORNHAUPT',to_timestamp('02.03.22 14:01:47,816195000','DD.MM.RR HH24:MI:SSXFF'),'1',null);
Insert into WOHNUNG.WVG_SOZIALE_ANGELEGENHEIT (ID,SAG_SONSTIGE_GRUENDE,SAG_SONSTIGE_GR_TXT,SAG_BEW_BEZIRKSWHG,SAG_SCHWERBEHINDERUNG,SAG_GDHL_GRUENDE,SAG_WOHNUNGSKUENDIGUNG,SAG_GR_WHGKUENDIGUNG,SAG_PFLEGE_ANGEH,CREATED_ON,CREATED_BY,MODIFIED_BY,MODIFIED_ON,SAG_ATS_ID,SAG_ENTF_ARBEITSPLATZ) values ('2','3',null,'nein',null,null,null,null,null,to_timestamp('01.03.22 06:59:30,649169000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT','ROD42201',to_timestamp('02.03.22 10:03:39,815476000','DD.MM.RR HH24:MI:SSXFF'),'4',null);
--------------------------------------------------------
--  DDL for Index PRIMARYKEYSOZIALEANGEL
--------------------------------------------------------

  CREATE UNIQUE INDEX "WOHNUNG"."PRIMARYKEYSOZIALEANGEL" ON "WOHNUNG"."WVG_SOZIALE_ANGELEGENHEIT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRIG_WVG_SOZIALE_ANGELEGENHEIT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "WOHNUNG"."TRIG_WVG_SOZIALE_ANGELEGENHEIT" 
BEFORE UPDATE OR INSERT ON WVG_SOZIALE_ANGELEGENHEIT 
FOR EACH ROW 
BEGIN 
IF :new.id is NULL
THEN 
 SELECT to_number(seq_wvg_soziale_angelegenheit.NEXTVAL) INTO :new.id FROM dual;
END IF;
    IF inserting THEN
        :new.created_on := localtimestamp;
        :new.created_by := nvl(wwv_flow.g_user,user);
    END IF;
IF updating THEN
:new.modified_on := localtimestamp;
:new.modified_by := nvl(wwv_flow.g_user,user);
    END IF;
END;
/
ALTER TRIGGER "WOHNUNG"."TRIG_WVG_SOZIALE_ANGELEGENHEIT" ENABLE;
--------------------------------------------------------
--  Constraints for Table WVG_SOZIALE_ANGELEGENHEIT
--------------------------------------------------------

  ALTER TABLE "WOHNUNG"."WVG_SOZIALE_ANGELEGENHEIT" ADD CONSTRAINT "PRIMARYKEYSOZIALEANGEL" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WVG_SOZIALE_ANGELEGENHEIT
--------------------------------------------------------

  ALTER TABLE "WOHNUNG"."WVG_SOZIALE_ANGELEGENHEIT" ADD CONSTRAINT "FRK_WVG_SOZIALE_ANGEL_ATS_ID" FOREIGN KEY ("SAG_ATS_ID")
	  REFERENCES "WOHNUNG"."WVG_ANTRAGSSTELLER" ("ID") ON DELETE CASCADE ENABLE;
