--------------------------------------------------------
--  Datei erstellt -Freitag-März-04-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table WVG_PERSONENHAUSHALT
--------------------------------------------------------

  CREATE TABLE "WOHNUNG"."WVG_PERSONENHAUSHALT" 
   (	"ID" NUMBER, 
	"PSH_WOHNSITZ_DT" NUMBER, 
	"PSH_KD_VDGESCHL" VARCHAR2(4 BYTE), 
	"PSH_KD_DAUERHAFT_AZ" NUMBER, 
	"PSH_KD_TEILWEISE_AZ" NUMBER, 
	"CREATED_BY" VARCHAR2(255 BYTE), 
	"CREATED_ON" TIMESTAMP (6), 
	"MODIFIED_BY" VARCHAR2(255 BYTE), 
	"MODIFIED_ON" TIMESTAMP (6), 
	"PSH_ATS_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "WOHNUNG"."WVG_PERSONENHAUSHALT"."ID" IS 'Primäre Schlüssel Datensatz';
   COMMENT ON COLUMN "WOHNUNG"."WVG_PERSONENHAUSHALT"."PSH_WOHNSITZ_DT" IS 'Anzahl Personen mit Wohnsitz Deutschland';
   COMMENT ON COLUMN "WOHNUNG"."WVG_PERSONENHAUSHALT"."PSH_KD_VDGESCHL" IS 'sind  Kinder verschiedengeschlechtlich';
   COMMENT ON COLUMN "WOHNUNG"."WVG_PERSONENHAUSHALT"."PSH_KD_DAUERHAFT_AZ" IS 'Kinderanzahl  dauerhaft im Haushalt ';
   COMMENT ON COLUMN "WOHNUNG"."WVG_PERSONENHAUSHALT"."PSH_KD_TEILWEISE_AZ" IS 'Kinderanzahl  teilweise  im Haushalt ';
   COMMENT ON COLUMN "WOHNUNG"."WVG_PERSONENHAUSHALT"."CREATED_BY" IS 'Ersteller Datensatz';
   COMMENT ON COLUMN "WOHNUNG"."WVG_PERSONENHAUSHALT"."CREATED_ON" IS 'Timestamp Erstellung  Datensatz';
   COMMENT ON COLUMN "WOHNUNG"."WVG_PERSONENHAUSHALT"."MODIFIED_BY" IS 'Benutzernamen Änderer des Datensatzes';
   COMMENT ON COLUMN "WOHNUNG"."WVG_PERSONENHAUSHALT"."MODIFIED_ON" IS 'Timestamp Änderung  Datensatz';
   COMMENT ON COLUMN "WOHNUNG"."WVG_PERSONENHAUSHALT"."PSH_ATS_ID" IS 'Fremdschlüssel zu Antragssteller';
   COMMENT ON TABLE "WOHNUNG"."WVG_PERSONENHAUSHALT"  IS 'Daten zu haushalten der Antragssteller';
REM INSERTING into WOHNUNG.WVG_PERSONENHAUSHALT
SET DEFINE OFF;
Insert into WOHNUNG.WVG_PERSONENHAUSHALT (ID,PSH_WOHNSITZ_DT,PSH_KD_VDGESCHL,PSH_KD_DAUERHAFT_AZ,PSH_KD_TEILWEISE_AZ,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_ON,PSH_ATS_ID) values ('2','12','ja','5','2','JUDITH.BORNHAUPT',to_timestamp('01.03.22 06:58:53,434780000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',to_timestamp('01.03.22 07:01:58,008530000','DD.MM.RR HH24:MI:SSXFF'),'4');
Insert into WOHNUNG.WVG_PERSONENHAUSHALT (ID,PSH_WOHNSITZ_DT,PSH_KD_VDGESCHL,PSH_KD_DAUERHAFT_AZ,PSH_KD_TEILWEISE_AZ,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_ON,PSH_ATS_ID) values ('3',null,null,null,null,'JUDITH.BORNHAUPT',to_timestamp('01.03.22 10:54:32,557560000','DD.MM.RR HH24:MI:SSXFF'),null,null,'2');
Insert into WOHNUNG.WVG_PERSONENHAUSHALT (ID,PSH_WOHNSITZ_DT,PSH_KD_VDGESCHL,PSH_KD_DAUERHAFT_AZ,PSH_KD_TEILWEISE_AZ,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_ON,PSH_ATS_ID) values ('4',null,null,null,null,'JUDITH.BORNHAUPT',to_timestamp('01.03.22 12:45:48,289804000','DD.MM.RR HH24:MI:SSXFF'),null,null,'6');
Insert into WOHNUNG.WVG_PERSONENHAUSHALT (ID,PSH_WOHNSITZ_DT,PSH_KD_VDGESCHL,PSH_KD_DAUERHAFT_AZ,PSH_KD_TEILWEISE_AZ,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_ON,PSH_ATS_ID) values ('5','5','ja','3','2','JUDITH.BORNHAUPT',to_timestamp('02.03.22 08:17:08,199408000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',to_timestamp('02.03.22 14:07:48,869455000','DD.MM.RR HH24:MI:SSXFF'),'10');
Insert into WOHNUNG.WVG_PERSONENHAUSHALT (ID,PSH_WOHNSITZ_DT,PSH_KD_VDGESCHL,PSH_KD_DAUERHAFT_AZ,PSH_KD_TEILWEISE_AZ,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_ON,PSH_ATS_ID) values ('1','5','ja','4','1','JUDITH.BORNHAUPT',to_timestamp('28.02.22 12:46:36,752448000','DD.MM.RR HH24:MI:SSXFF'),'JUDITH.BORNHAUPT',to_timestamp('02.03.22 14:01:10,610016000','DD.MM.RR HH24:MI:SSXFF'),'1');
--------------------------------------------------------
--  DDL for Index PRIMARYKEYPERSONENHAUSHALT
--------------------------------------------------------

  CREATE UNIQUE INDEX "WOHNUNG"."PRIMARYKEYPERSONENHAUSHALT" ON "WOHNUNG"."WVG_PERSONENHAUSHALT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRIG_WVG_PERSONENHAUSHALT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "WOHNUNG"."TRIG_WVG_PERSONENHAUSHALT" 
BEFORE UPDATE OR INSERT ON WVG_PERSONENHAUSHALT 
FOR EACH ROW 
BEGIN 
IF :new.id is NULL
THEN 
 SELECT to_number(seq_wvg_personenhaushalt.NEXTVAL) INTO :new.id FROM dual;
END IF;
    IF inserting THEN
        :new.created_on := localtimestamp;
        :new.created_by := nvl(wwv_flow.g_user,user);
    END IF;
IF updating THEN
:new.modified_on := localtimestamp;
:new.modified_by := nvl(wwv_flow.g_user,user);
    END IF;
END;
/
ALTER TRIGGER "WOHNUNG"."TRIG_WVG_PERSONENHAUSHALT" ENABLE;
--------------------------------------------------------
--  Constraints for Table WVG_PERSONENHAUSHALT
--------------------------------------------------------

  ALTER TABLE "WOHNUNG"."WVG_PERSONENHAUSHALT" ADD CONSTRAINT "PRIMARYKEYPERSONENHAUSHALT" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WVG_PERSONENHAUSHALT
--------------------------------------------------------

  ALTER TABLE "WOHNUNG"."WVG_PERSONENHAUSHALT" ADD CONSTRAINT "frk_wvg_ph_ats_id" FOREIGN KEY ("PSH_ATS_ID")
	  REFERENCES "WOHNUNG"."WVG_ANTRAGSSTELLER" ("ID") ON DELETE CASCADE ENABLE;
